Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    # Environment:
    #   Variables:
    #     X:Y
    Runtime: nodejs14.x
    MemorySize: 128
    Timeout: 30
    Layers:
      - !Ref LambdaLayer

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - OPTIONS
          - DELETE
          - PUT
        AllowHeaders:
          - Authorization
          - Access-Control-Allow-Origin
          - Content-Type
        AllowOrigins:
          - "*"
      AccessLogSettings:
        DestinationArn: !GetAtt HttpApiAccessLogs.Arn
        Format: $context.requestId

  HttpApiAccessLogs:
    Type: AWS::Logs::LogGroup

  LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "${AWS::StackName}-dependencies"
      Description: Some code to share with the API
      ContentUri: src/layers
      CompatibleRuntimes:
        - nodejs14.x
      RetentionPolicy: Delete

  FunctionAccountGet:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-test-get"
      CodeUri: src/account/
      Handler: get.handler
      Description: A function to get account
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /account
            Method: GET
            ApiId: !Ref HttpApi

Outputs:
  HttpApiUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}"
