name: sam-build-deployment

on:
  push:
    branches:
      - dev
      - main

jobs:
  deployment:
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    env:
        SAM_CLI_TELEMETRY: 0
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: actions/setup-python@v3
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: npm ci --quiet --production --prefix layers/nodejs
      - run: sam build --use-container
      - run: sam package --template-file .aws-sam/build/template.yaml --s3-bucket ${{ secrets.AWS_S3_BUCKET }} --s3-prefix ${{ github.ref_name }}/${{ github.sha }} --output-template-file .aws-sam/build/template-packaged.yaml
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --capabilities CAPABILITY_IAM --template-file .aws-sam/build/template-packaged.yaml --region ${{ secrets.AWS_REGION }} --stack-name entu-api-${{ github.ref_name }} --parameter-overrides GitSha=${{ github.sha }} DomainName=${{ secrets.DOMAIN }} CertificateArn=${{ secrets.AWS_CERT_ARN }} HostedZoneId=${{ secrets.AWS_ZONE_ID }} MongoDbUrl=${{ secrets.MONGODB_URL }} JwtSecret=${{ secrets.JWT_SECRET }}
      - run: echo "-- DEPLOY DONE --"
